### ISSUE TITLE
Error occurs when a folder is selected instead of a file

### ISSUE THREAD

**Issue by tombout** [tombout/SublimeMql5LanguagePack#1]
When I select a folder in Sublime and press the short cut for the Mql5Compiler (crtl+alt+m) following stacktrace is shown in the Sublime Console:

<code>
Traceback (most recent call last):
  File "C:\Users\Thomas\Dropbox\Portables\Sublime Text 3\sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "C:\Users\Thomas\Dropbox\Portables\Sublime Text 3\Data\Packages\SublimeMql5Compiler\mql5_compiler.py", line 66, in run
    if self.isError():
  File "C:\Users\Thomas\Dropbox\Portables\Sublime Text 3\Data\Packages\SublimeMql5Compiler\mql5_compiler.py", line 31, in isError
    if self.extension not in EXTENSION:
</code>

**Comment by tombout** [comment]
Is fixed with one of the last commits. The compiler plugin works more stable now.
